# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.coilhead.bone.coilhead_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coilhead_body set from storage aj:uuid main.out