# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.masked.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'masked', 'function_path': 'animated_java:masked/animations/pause_all'}
tag @s remove aj.masked.animation.animation_masked_armsway.playing
tag @s remove aj.masked.animation.animation_masked_walklegs.playing
tag @s remove aj.masked.animation.animation_masked_walkarms.playing
tag @s remove aj.masked.animation.animation_masked_armsout.playing
tag @s remove aj.masked.animation.animation_masked_run.playing
tag @s remove aj.masked.animation.animation_masked_scale.playing