# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:masked/animations/animation_masked_armsway/zzz/apply_frame {frame: 30}
scoreboard players add @s aj.animation_masked_armsway.frame 1