# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.soj.root] run return 0
execute on passengers if entity @s[tag=aj.soj.data] unless data entity @s {data:{rigHash: 'ef7973db99588009a532384c7613597a92999bdeca1ab7c7b837730c17336259'}} on vehicle run function animated_java:soj/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1