# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:soj/animations/animation_soj_idle/zzz/apply_frame {frame: 85}
scoreboard players add @s aj.animation_soj_idle.frame 1