# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.coilhead.root] run return 0
execute on passengers if entity @s[tag=aj.coilhead.data] unless data entity @s {data:{rigHash: '3333f24a7d2e28946907a465afe3823adb245eea54e780478915add20c10f772'}} on vehicle run function animated_java:coilhead/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1