# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.coilhead.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:coilhead/as_root/pre_tick
execute if entity @s[tag=aj.coilhead.animation.animation_coilhead_stop.playing] run function animated_java:coilhead/animations/animation_coilhead_stop/zzz/on_tick
execute on passengers if entity @s[tag=aj.coilhead.data] run function animated_java:coilhead/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:coilhead/as_root/post_tick