# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:masked/animations/animation_masked_scale/zzz/apply_frame {frame: 1}
scoreboard players add @s aj.animation_masked_scale.frame 1