# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.animation_masked_armsway.frame dummy
scoreboard objectives add aj.animation_masked_walklegs.frame dummy
scoreboard objectives add aj.animation_masked_walkarms.frame dummy
scoreboard objectives add aj.animation_masked_armsout.frame dummy
scoreboard objectives add aj.animation_masked_run.frame dummy
scoreboard objectives add aj.animation_masked_scale.frame dummy