# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.masked.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:masked/as_root/pre_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_armsway.playing] run function animated_java:masked/animations/animation_masked_armsway/zzz/on_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_walklegs.playing] run function animated_java:masked/animations/animation_masked_walklegs/zzz/on_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_walkarms.playing] run function animated_java:masked/animations/animation_masked_walkarms/zzz/on_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_armsout.playing] run function animated_java:masked/animations/animation_masked_armsout/zzz/on_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_run.playing] run function animated_java:masked/animations/animation_masked_run/zzz/on_tick
execute if entity @s[tag=aj.masked.animation.animation_masked_scale.playing] run function animated_java:masked/animations/animation_masked_scale/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~
function #animated_java:masked/as_root/post_tick